name: EdgeCrafter
favicon: null
layout_spectrum: 0.5414519440382719
typography_spectrum: 0.25145682599395514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7849870757199824
  lightness: 0.13497554161585867
  saturation: 0.616692695999518
  rhythmicContrast: 0.8489243271760643
purpose: []
